@startuml
allow_mixing

actor user
component client

component cloud {
    component gateway {
        component api
        component webSocket
        component apiGateway
    }

    component s3 {
        object clientBucket
    }

    component lambdaFns {
        class getGame
        class playMove
        class subscribeToGame
        class createGame
        class getOpenGames
        class joinGame

        diamond apiDiamond
        circle updateSubscribers
    }

    component ddb {
        object GameTable
        object ConnectionTable
        object openGamesTable
    }

    circle writeGameTable
}

apiGateway --> clientBucket
user --> client
user --> apiGateway: fetch client
client --> api
client <--> webSocket

apiDiamond --> getGame
getGame --> GameTable: get

apiDiamond --> playMove
playMove --> writeGameTable
playMove -up-> updateSubscribers

apiDiamond --> createGame
createGame --> openGamesTable: add
createGame --> writeGameTable

apiDiamond --> getOpenGames
getOpenGames --> openGamesTable: scan

apiDiamond --> joinGame
joinGame --> writeGameTable
joinGame --> openGamesTable: delete
joinGame -up-> updateSubscribers

webSocket --> subscribeToGame
subscribeToGame -> ConnectionTable: write

updateSubscribers --> ConnectionTable: list
updateSubscribers -up-> webSocket

writeGameTable --> GameTable
api --> apiDiamond

@enduml